### ISSUE TITLE
SVG assets unrenderable  in Chrome (maybe)

### ISSUE THREAD

**Issue by bronius** [JJJ/chosen#36]
Summarize your issue here.

All css/svg sprite icons are unrenderable in my Chrome on Mac. I've spot-checked them by w3c validator to confirm the same. This is right from vanilla 2.2.0 assets from the compiled ./docs folder.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Open a JJJ Chosen multiselect in a page.

  2. Select an item.

  3. See that no icon shows to deselect the item (but the transparent button does respond to a hover and a click).

  4. Open the expected background icon inline svg uri in browser tab, see error `error on line 1 at column 96: AttValue: ' expected` and similar error in w3c validator:
https://validator.w3.org/check?uri=data%3Aimage%2Fsvg%2Bxml%3Bcharset%3DUS-ASCII%2C%3Csvg+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22+width%3D%2256%22+height%3D%2256%22+viewBox%3D%220+0+56+56%22%3E%3Cpath+fill%3D%22%23888%22+d%3D%22M+27.9999+51.9063+C+41.0546+51.9063+51.9063+41.0781+51.9063+28+C+51.9063+14.9453+41.0312+4.0937+27.9765+4.0937+C+14.8983+4.0937+4.0937+14.9453+4.0937+28+C+4.0937+41.0781+14.9218+51.9063+27.9999+51.9063+Z+M+19.5858+38.4063+C+18.4843+38.4063+17.5936+37.5156+17.5936+36.4141+C+17.5936+35.8750+17.8280+35.4063+18.2030+35.0547+L+25.1874+28.0234+L+18.2030+20.9922+C+17.8280+20.6641+17.5936+20.1719+17.5936+19.6328+C+17.5936+18.5547+18.4843+17.6875+19.5858+17.6875+C+20.1249+17.6875+20.5936+17.8984+20.9452+18.2734+L+27.9765+25.2812+L+35.0546+18.25+C+35.4530+17.8281+35.8749+17.6406+36.3905+17.6406+C+37.4921+17.6406+38.3827+18.5312+38.3827+19.6094+C+38.3827+20.1484+38.1952+20.5937+37.7968+20.9688+L+30.7655+28.0234+L+37.7733+35.0078+C+38.1249+35.3828+38.3593+35.8516+38.3593+36.4141+C+38.3593+37.5156+37.4687+38.4063+36.3671+38.4063+C+35.8046+38.4063+35.3358+38.1719+34.9843+37.8203+L+27.9765+30.7890+L+20.9921+37.8203+C+20.6405+38.1953+20.1249+38.4063+19.5858+38.4063+Z%22%2F%3E%3C%2Fsvg%3E&charset=%28detect+automatically%29&doctype=Inline&group=0

Note, this can also be seen on the JJJ chosen project demo page:
https://jjj.github.io/chosen/
![example_on_examples_page](https://user-images.githubusercontent.com/2348390/95344427-41a2f700-087f-11eb-8724-8568bbe0a3dc.jpg)

### Environment

  - **Chosen Version**: 2.2.0

  - **jQuery or Prototype Version**: 3.5.1

  - **Browser and Version**: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

  - **OS and Version**: Mac Catlina (10.15.6)

### Additional information

Thank you for maintaining this important and awesome project!

**Comment by JJJ** [comment]
I can't figure out the proper syntax for UTF-8 or US-ASCII, so going to use base64 for 2.2.1.
