### ISSUE TITLE
Add this library on Packagist

### ISSUE THREAD

**Issue by hussainweb** [JJJ/chosen#40]
This library is not available on [Packagist](https://packagist.org/). This means that one of the installation instructions using composer doesn't work. There is a workaround where we can add a [custom repository](https://getcomposer.org/doc/05-repositories.md) in composer.json but the fix is straightforward. The problem is that the maintainer needs to do this.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Use any PHP project or start a new one with `composer init` (this is optional).
  2. Run the installation command as in the README: `composer require jjj/chosen`

It's not a JavaScript error, so I can't show this anyplace but I am happy to share a screenshot. This is the error though:
```
  [InvalidArgumentException]                                                                                                                      
  Could not find a matching version of package jjj/chosen. Check the package spelling, your version constraint and that the package is available  
   in a stability which matches your minimum-stability (dev). 
```

### Expected behavior

Installation should work

### Actual behavior

Error as described above

### Environment

  - **Chosen Version**: N/A

  - **jQuery or Prototype Version**: N/A

  - **Browser and Version**: N/A

  - **OS and Version**: macOS with PHP 7.4 but I believe this shouldn't matter

### Additional information

The "fix" for this is relatively simple (thanks to the `composer.json` which is already in this repo). The maintainer just needs to add this to packagist. I tried adding it but couldn't as there is already [a package under JJJ namespace](https://packagist.org/packages/jjj/). The maintainer (I am assuming @JJJ) has added the previous package and needs to add this as well. [Adding the package](https://packagist.org/packages/submit) is fairly simple and I can help with that if required.

**Comment by JJJ** [comment]
Done! Apologies for the extended silence. 🙏
