### ISSUE TITLE
a11y: collapsed combobox it is announced as “expanded” for screen readers

### ISSUE THREAD

**Issue by jenlampton** [JJJ/chosen#42]
When landing on the collapsed (closed) combobox, it is announced as “expanded”. This is because the `aria-expanded` value is changing to “true” on focus, rather than after the user expands the listbox. 

The following is the code where the problem occurs:
`<input class="chosen-search-input" type="text" role="combobox" aria-expanded="true"...`

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Enable JAWS
  2. Tab into the element using chosen, but do not expand
  3. Listen for the announcement for expanded/collapsed

Additionally, please link to a working demo that shows the issue so we can attempt to reproduce.  
https://chosen-jjj-abag2.pantheonsite.io/meetings 
The "choose a meeting" element at top right

### Expected behavior

the `aria-expanded` value is changing to “true” only after the combo box is explicitly opened

### Actual behavior

the `aria-expanded` value is changing to “true” on focus

### Environment

  - **Chosen Version**: 2.2.1 

  - **jQuery or Prototype Version**: jQuery 3.6.0

  - **Browser and Version**: Chrome Version 105.0.5195.125 (Official Build) (arm64)

  - **OS and Version**: Mac OS 12.6

**Comment by juanolalla** [comment]
Solved in pull request: https://github.com/JJJ/chosen/pull/43

**Comment by JJJ** [comment]
Thank you @jenlampton & @juanolalla!

PR merged 🙏
